[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "lipschitz-regularization"
version = "1.0.0"
readme = "README.md"
dependencies = [
    "cython",
    "numpy",
    "matplotlib"
]
